# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luc Blassel
bio: 'Getting to know machine learning'
description: >- # this means to ignore newlines until "baseurl:"
  understanding machine learning and how it works
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lucblassel.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: zlanderous/zlanderous.github.io

linkedin_username: luc-blassel
github_username:  lucblassel
timezone: Europe/Paris
show_excerpts: true

mathjax: true
# disqus:
#   shortname: zlanderous-github-io

disqus_shortname: zlanderous-github-io

# Build settings
markdown: kramdown
highlighter: rouge

# theme: minima
remote_theme: TaylanTatli/Moon
logo: assets/images/logo_color.svg

defaults:
  -
    values:
      author: Luc Blassel

google:
  analytics: UA-135923392-1

github-url:         zlanderous
stackoverflow:      8650928/luc-blassel
linkedin:           luc-blassel
instagram:          zlanderous

# theme_color: red
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
